election-portal/app/globals.css, election-portal/package-lock.json, election-portal/package.json
=> add css gradient

election-portal/app/modules/menubar/menu-buttons/exit-button.tsx, election-portal/app/modules/menubar/menubar.css, election-portal/app/modules/menubar/menubar.tsx, election-portal/app/sharedContext.tsx, election-portal/types/Year.ts
=> remove house, dynamic years, dynamic exit button

election-portal/app/modules/canvas/canvas.css
=> adding a slight drop shadow to drawn lines

election-portal/app/road-to-control/modules/RTCMap.tsx
Made the graph so it is always either all red or all blue, and changed some of the data. Feel free to not accept this change, but the graph should not be on a gradient regardless, so that's something worth fixing.
=> Removed hover from RTC, and made it all blue or all red

.gitignore, election-portal/app/election-breakdown/modules/banner.css, election-portal/app/exit-poll-explorer/modules/exit-poll-map.css, election-portal/app/exit-poll-explorer/modules/exit-poll-map.tsx, election-portal/app/exit-poll-explorer/modules/statistics-table.css, election-portal/app/exit-poll-explorer/modules/statistics-table.tsx, election-portal/app/exit-poll-explorer/page.module.css, election-portal/app/exit-poll-explorer/page.tsx, election-portal/app/modules/menubar/menubar.css, election-portal/app/modules/menubar/menubar.tsx, election-portal/app/road-to-control/page.tsx, election-portal/app/sharedContext.tsx, election-portal/types/Demographic.ts, election-portal/types/SharedInfoType.ts
@akslaym Hi Akshay! You mentioned doing the work to get the exit poll statistics from the CSV file on the frontend. I'm worried that might not be a good idea and was wondering if there's some way to do it on the backend? If not, then could it be made into a separate task, and I'll get to it later? Thank you!
https://github.com/orgs/BPR-Data-Team/projects/2/views/6?pane=issue&itemId=82249085&issue=BPR-Data-Team%7CElection-Night%7C118
https://github.com/orgs/BPR-Data-Team/projects/2/views/6?pane=issue&itemId=82249221&issue=BPR-Data-Team%7CElection-Night%7C121
https://github.com/orgs/BPR-Data-Team/projects/2/views/6?pane=issue&itemId=82249295&issue=BPR-Data-Team%7CElection-Night%7C122
=> Exit poll frontend

decision_desk/Dashboard/Dashboard Utilities/Plotting.R, decision_desk/Dashboard/Dashboard.R
When I changed the way files were organized earlier, there were some problems -- this fixes the dashboard references
=> Change dashboard references

decision_desk/E-Day Scraping and Model.R, decision_desk/HistoricalElections.R
=> Fixed problems with VT/NH where one of the counties had the wrong FIPS code

decision_desk/E-Day Scraping and Model.R
Added hmisc package, makes it far easier for Akshay -- now he just needs to download these specific packages and NO more!
=> Added Hmisc package to make it easier for Akshay on the BE

decision_desk/Dashboard/Dashboard.R
=> Added map selector, races to watch, races to call, closing times, time to poll close, electoral vote tally

decision_desk/Dashboard/Dashboard Utilities/TimeToNextPoll.R, decision_desk/Dashboard/Dashboard.R
merging this before asher blows it all up again
=> Election select

election-portal/app/election-breakdown/modules/banner.css, election-portal/app/election-breakdown/modules/dataDisplay.css, election-portal/app/election-breakdown/modules/stateMap.tsx
so text doesnt randomly get highlighted
=> Pointer events

election-portal/app/election-breakdown/modules/stateMap.tsx
it doesn't work for most states except for alabama since we don't have non-mocked state/series data for highcharts
=> state oob handling

election-portal/app/election-breakdown/modules/banner.css, election-portal/app/exit-poll-explorer/modules/statistics-table.css, election-portal/app/exit-poll-explorer/page.tsx, election-portal/app/modules/menubar/menubar.css
Removed comments and console logs from exit poll page, improved font consistency, and changed the banner for exit polls.
=> Minor styling

election-portal/app/election-breakdown/modules/EBMap.tsx, election-portal/app/modules/canvas/canvas.tsx, election-portal/app/modules/menubar/menu-buttons/draw-button.module.css
changed draw color and made button color in sidebar match
=> feat: change draw color

election-portal/app/election-breakdown/modules/EBMap.tsx, election-portal/app/election-breakdown/modules/mapDataCache.tsx, election-portal/app/election-breakdown/modules/stateMap.tsx
-  Makes sure that the menubar options are updated for states that don't have gub./sen. data  #299 
- We don't have 2012 geoJSON data, so we use the 2022 data in that case
=> EB state map menubar options

election-portal/app/election-breakdown/modules/EBMap.tsx
=> make green outline show on top

election-portal/app/road-to-control/modules/ElectoralVoteButton.tsx, election-portal/app/road-to-control/modules/RTCMap.tsx
Changes:
I seperated the originalMap into mapData and circleValues so the districts do not overwrite the actual state.
=> Circle maine error

election-portal/app/exit-poll-explorer/modules/EXMap.css, election-portal/app/exit-poll-explorer/modules/EXMap.tsx, election-portal/app/exit-poll-explorer/modules/mapDataCache.tsx, election-portal/app/exit-poll-explorer/modules/stateMapEX.css, election-portal/app/exit-poll-explorer/modules/stateMapEX.tsx, election-portal/app/exit-poll-explorer/page.module.css, election-portal/app/exit-poll-explorer/page.tsx, election-portal/app/modules/menubar/menubar.css, election-portal/app/modules/menubar/menubar.tsx, election-portal/app/sharedContext.tsx
- akshay's frontend code
- added scrollbar to side menu
- added websocket reconnect code
=> Exit polls akshay

election-portal/app/election-breakdown/modules/dataDisplay.tsx
it wasnt in the useeffect callbacks
=> update statename in data display

election-portal/app/exit-poll-explorer/page.tsx, election-portal/app/sharedContext.tsx
=> fixed issue with maps not populating
